### ISSUE TITLE
Ember3 upgrade - ran into issue with scheduler never exiting

### ISSUE THREAD

**Issue by josh803316** [html-next/ember-raf-scheduler#5] opened 2018-03-21 21:02 UTC
I have upgraded a component library to Ember3 which is using `"@html-next/vertical-collection": "1.0.0-beta.10"` for one of our grids. I noticed after I upgraded, during the test for that grid, that the scheduler seems to be stuck with in a never ending loop.

```javascript
function registerWaiter() {
    // We can't rely on the importable Ember since shims are no
    // longer included by default, so use the global instance.
    // eslint-disable-next-line
    Ember.Test.registerWaiter(function () {
      return _emberRafScheduler.default.jobs === 0;  // THIS value is stuck at 1
    });
  }
```

tests/test_helpers.js
```javascript
import Application from '../app';
import registerWaiter from 'ember-raf-scheduler/test-support/register-waiter';
import config from '../config/environment';
import { setApplication } from '@ember/test-helpers';

import resolver from './helpers/resolver';
import { setResolver } from '@ember/test-helpers';
import { start } from 'ember-qunit';

setResolver(resolver);

registerWaiter();

setApplication(Application.create(config.APP));
start();

```

I also saw a separate test fail that was passing with:
`Tried to restart test while already started (test's semaphore was 0 already)` 
but I wasn't sure if it was related.

Any guidance would be appreciated.

**Comment by mixonic** [comment] 2023-04-10 14:24
Closing this, as I think https://github.com/html-next/vertical-collection/issues/320 triaged this to a more narrow root cause (multiple v-c instance with the same container selector).

Please feel free to re-open, especially if there is an issue reproducible with the latest release. Generally, that release is widely used with Ember 3 and 4.

**Closed as completed by mixonic** 2023-04-10 14:24 UTC
